"""tasks table

Revision ID: 704746f82904
Revises: 
Create Date: 2021-04-09 16:02:07.534236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704746f82904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_task'), 'task', ['task'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_task'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
